//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crossroads.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Church
    {
        public int Id { get; set; }
        public string CName { get; set; }
        public string CAddress { get; set; }
        public string CCity { get; set; }
        public string CState { get; set; }
        public string CZipCode { get; set; }
        public string CPhone { get; set; }
        public string CWebsite { get; set; }
        public string PTName { get; set; }
        public string Logo { get; set; }
    }
}
