//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crossroads.database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class entities : DbContext
    {
        public entities()
            : base("name=entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Church> Churches { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<ServiceSong> ServiceSongs { get; set; }
        public virtual DbSet<ServiceUnavailable> ServiceUnavailables { get; set; }
        public virtual DbSet<ServiceUser> ServiceUsers { get; set; }
        public virtual DbSet<Song> Songs { get; set; }
        public virtual DbSet<SongsWishList> SongsWishLists { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
