//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crossroads.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public System.DateTime ServiceDate { get; set; }
        public string ServiceTitle { get; set; }
        public string ServiceScripture { get; set; }
        public string ServicePDF { get; set; }
        public string ServiceNotes { get; set; }
        public bool Baptism { get; set; }
        public bool Communion { get; set; }
        public bool Rehearsal { get; set; }
        public int Id { get; set; }
        public int ChurchId { get; set; }
    }
}
