//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crossroads.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceSong
    {
        public int ServiceId { get; set; }
        public int SongId { get; set; }
        public Nullable<int> SongLeadUser { get; set; }
        public string SongPosition { get; set; }
        public int Id { get; set; }
    }
}
