//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crossroads.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SongsWishList
    {
        public string Status { get; set; }
        public string PType { get; set; }
        public string Title { get; set; }
        public string Artist { get; set; }
        public string Link { get; set; }
        public string Notes { get; set; }
        public System.DateTime DateRequested { get; set; }
        public string Requestor { get; set; }
        public int Id { get; set; }
        public int ChurchId { get; set; }
    }
}
